### ISSUE TITLE
Navrh: pozadi DO

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#102]
Jakmile je to dlouhá stránka, tohle vyměněné pozadí najednou končí a následuje velká černá tma. Černá díra? :-) Nevypadalo by třeba dobře statický usazení pozadí? Zvlášť pokud se tedy uvažuje, že budeme mít možnost uživatelský volby pozadí.
http://beta.dunaonline.cz/topics/193

**Comment by Tar-Gilkaltar** [comment]
Původní návrh měl hvězdy všude. Bylo to ale odstraněno a znovu se mi to psat nechce.
