### ISSUE TITLE
Otazka: Renegati

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#114]
Budou hratelnou rasou? Tzn. osidlování lén, zástavba, nákup jednotek, politika... Zatím to tak vypadá
http://beta.dunaonline.cz/topics/210

**Comment by janpadrta** [comment]
principielně můžou dělat vše normálně, ale do Landsraadu se nedostanou, ani Impem, regentem vezírem či dvořanem být nemůžou. a nedostávají melanž z IS
