### ISSUE TITLE
Navrh: hracovo postaveni v politice a redukce poctu mentatu

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#115]
jeden hrac muze byt zaroven vudcem naroda, poslancem i tim tretim, vrcholnym politikem 
neslo by, aby byl bud vudcem nebo vrcholnym politikem a nebo jen poslancem? Aspon se pak vic hracu zapoji do aktivni casti hry a chapu ze nekteri budou tvrdit ze to rikam i kvuli sobe :) a omezit pocet vrcholnych politiku? treba na 5? :)
http://beta.dunaonline.cz/topics/211

**Comment by Tar-Gilkaltar** [comment]
Nemyslím si, že je to dobře. Vrcholni politici jsou o přístupu do skladů. A pokud to omezíme, přídáme jen práci s přehazováním hodností při dovolených ap.
