### ISSUE TITLE
Bug: General vyhostil sebe, malorod bez generala

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#120]
General vyhostil sam sebe, po prepoctu, malorod ma jen vicegenerala a chybi General

**Comment by Tar-Gilkaltar** [comment]
To bylo na staré duně také. A generál byl zvolen novy. 
Zůstala mu hodnost i po vyhozeni?

**Comment by minohimself** [comment]
asi mysli ze potom do prepoctu nemali pristup ku skladom, ak to je ten case mozem spravit ze dalsi najviac hlasov dostane generala
