### ISSUE TITLE
Bug: volba poslancu

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#125]
Ve sprave hrace vidim seznam 5 hracu, kteri maji nejaky hlas na poslance. Aktualne jsou 3 hraci po dvou hlasech a dva po jednom hlasu. V prehledu naroda vidim seznam sedmi poslancu. Predpokladam, ze tento seznam se aktualizuje az po prepoctu? Jinak si neumim vysvetlit, ze v nem neni uveden hrac, ktery ma nyni dva hlasy na poslance + ze v jednotlivych prehledech je ruzny pocet poslancu.
Druha vec je samotne hlasovani pro poslance. V seznamu s pocty hlasu je jeden z hacu, ktery ma dva hlasy na poslance a jeden z nich je muj. Pokud volbu zmenim a hlasuju pro sebe, tak dany hrac ze seznamu uplne vypadne, i kdyz ma mit stale jeden hlas. Bud je tam nejaky bug a nebo se zobrazuje pouze seznam prvnich 5 hracu s hlasy na poslance. Coz by ovsem bylo nestastne, jelikoz pri shode poctu hlasu neuvidim vsechny kandidaty a nemohu svym hlasem nektereho uprednostnit (jelikoz nevim ze vubec nejaky hlas ma) 
Takhle to mozna funguje u vsech hlasovani, ale jen u poslancu se mi to podarilo overit

http://beta.dunaonline.cz/topics/229

**Comment by Tar-Gilkaltar** [comment]
Volby na poslance probíhají 1 týdne. Tedy nemá vliv počet hlasu, dokud není přelom neděle/pondělí. Odtud asi vychází celkový problem. :)

Na tu top5 je potřeba se podívat.

**Comment by Alenil** [comment]
Muzes prozradit jak se vyberou poslanci pokud dojde pocet hracu kteri maji alespon jeden hlas?

**Comment by minohimself** [comment]
Olda?

**Comment by Alenil** [comment]
Rekneme, ze narod ma narok na 10 poslancu, ale hlas ve volbach jich ma jen 5. Jak se vybere tech zbyvajicich 5?

**Comment by minohimself** [comment]
nijako zobere to len tych piatich a spravi ich poslancom

**Comment by minohimself** [comment]
pocet_poslancu = h.pocet_poslancu

for u in h.poradi_hlasu('poslanec', pocet_poslancu) do
        u[0].update_attribute(:landsraad, true)
        u[0].zapis_operaci("Nyni jsem poslancem.")
      end

**Comment by Alenil** [comment]
Neni to chyba? To aby si narod prepocitaval kolik ma mit poslancu a podle toho rozdeloval hlasy. 
- neni nikde receny jestli se to dela po prepoctu a pridani vlivu nebo az pote. Tzn spocitam si ze mame narok na 5 poslancu, 5 lidi ma hlas, ale behem prepoctu dostanem vliv a mame narok na 6, ale pac nikdo dalsi nema hlas tak mame smulu a jen 5

**Comment by minohimself** [comment]
no podla mna je to tak je holt malo kandidatov, to bude asi zname kedy su volby nie ?

**Comment by Alenil** [comment]
To se pak muze stat ze v Landsraadu nebude plny pocet poslancu ale treba jen polovina. Ale asi je to lepsi nez tam davat nahodny hrace.
Jestli datum bude znamo tak Ok, zatim to nikde neni.

**Comment by minohimself** [comment]
A kde by to bolo dobre dat ?

2013/11/24 Alenil notifications@github.com

**Comment by Alenil** [comment]
Bud na nastenku, ale Doktor myslim psal ze jeste nejdou, nebo nad vyberovy box Senatora, Tzn do Sprava hrace a volby

**Comment by minohimself** [comment]
tak to nechame na neho

2013/11/24 Alenil notifications@github.com

**Comment by Doktoros** [comment]
datum voleb senátorů už jsem zobrazil, bohužel pod combobox výběru ;-) ale to je asi jedno ;-)

myslím si, že prázdný landsraad bude hrozit tak maximálně první volby... později s více hráči už ne...

**Comment by Tar-Gilkaltar** [comment]
Bug je opraven a nebo přetrvavá?
