### ISSUE TITLE
Bug: Zaporna melanz na ucte - Bill Joy

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#128]
Aaaa fesaci proc mam najednou -194.187,00 melanže? :-D prosim spravit, takhle nic nepostavim 
diky
http://beta.dunaonline.cz/topics/233

**Comment by Tar-Gilkaltar** [comment]
Odpoved podle ne najde ve výpisu, kdy mu jeho rod poslal -XXX. Relmi pls zkontroluj to. Jste ze stejného rodu ze?
