### ISSUE TITLE
Bug: Presun materialu na to same leno

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#130]
Kdyz presunu material z lena A na leno A (tedy na to same leno) ubere mi to solary, coz je logicky blbost.

**Comment by Tar-Gilkaltar** [comment]
jako poplatek za poslání sám sobě?:)

**Comment by relmi** [comment]
Stejne bych rekl, ze je chyba, ze mam ve vyberu pro presun leno, na kterem jsem. Ve vyberu by nejspis mely byt ostatni lena.
