### ISSUE TITLE
Chyba: nadpis syselaadu

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#131]
Vsechny syselaady maji nad jednotlivymi vlakny napis Syselaad, ale neni poznat o ktery se jedna 
Az kdyz se prokliknu do vlakna vidim v jakem syselu jsem
http://beta.dunaonline.cz/topics/244

**Comment by Tar-Gilkaltar** [comment]
Nejde o nadpis ale o ukončení drobečkové navigace. 

Nutno opravit v: 

syselaad/show
