### ISSUE TITLE
Navrh: Narodni akce

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#133]
Bylo by fajn mit vsechno, co se tyce velkorodu, na jednom miste - tedy ve sprave velkorodu. Ted jsou napriklad narodni akce videt jen z prehledu narodu (btw nemel by to byt prehled velkorodu?).

**Comment by Tar-Gilkaltar** [comment]
Jj přejmenování udělám dnes večer a pohraji si i s přehledem :)
