### ISSUE TITLE
Navrh: vlakna s omezenou viditelnosti

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#136]
V soucasny dobe, kdyz se chce skupina lidi na necem domluvit musi pres postu nebo mimo hru. Vzhledem k tomu, ze vsichni chceme aby se hralo ve hre tak by se mi libili vlakna s omezenym pristupem/viditelnosti 
V systemovem syselaadu - jen pro adminy(pro zavazne bugy co nemusi vedet cele imperium) 
V narodnim - pro mentaty,armymentaty,vedeni(mentati,diplomati+generalove) - s tim ze vudce by videl vsude 
V landsraadu - pro imperialni vedeni(imp,veziri,clenove dvora)

**Comment by Tar-Gilkaltar** [comment]
Pěkný nápad. Mohl by se zavést i s moderatory
