### ISSUE TITLE
Chyba: posunute casy ve vypisech

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#139]
čas v seznamu akcí malorodu je pravděpodobně o 2 hodiny posunutý:

Olda 
17.10.2013 00:42
nejen malorod 
Vliv naroda je nyni: 17.10.2013 22:15:36
datum spravne ale cas trochu mimo

http://beta.dunaonline.cz/topics/259

**Comment by minohimself** [comment]
duplicate
