### ISSUE TITLE
Otazka: Ekonomika objevování lén

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#141]
Když nad tím tak přemýšlím... Než proběhly o víkendu wipy, jak jsem měl nějakých 200 lén. Přišlo mi trochu škoda, že cena léna stála stejně člověka, který seděl na domovském, jako mě, který jich měl jako celé Impérium dohromady. 
Pokud platí vize, že až přibudou jednotky a obrana léna bude jednodušší, pokud na planetě budu mít další svá léna, zatím mi stále vychází, že co do investice do obrany a tím pádem i ekonomiky, je nejvýhodnější model zadotovat jednoho hráče, aby najednou zabral celou planetu. Ten pak může půl věku dotovat celý národ a ostatní si můžou spokojeně sedět na domovském léně.
Nebo prosím o osvětlení, jak mechanismy hry donutí národ, aby tohle nedělal :-)
Co do nastínění té obrany, mluvil o tom někde v nějakém vlákně Doktor a aspoň jsem to tak pochopil. Logické by mi například přišlo, kdyby se na mojí obraně nepodílela jen moje léna, ale i léna ostatních Corrino na planetě. Klidně nějakým menším poměrem.

http://beta.dunaonline.cz/topics/262

**Comment by Doktoros** [comment]
cena léna se nyní počítá podle celkové obsazenosti planety.
ale asi to fakt změníme a dodáme tam i závislost (lineární/kvadratická???) na vlastním počtu lén.
Ohledně obrany: 
jednotky na lénu brání dané léno. U planety budou umístěny flotily. Pokud se někdo pokusí vylodit na nové léno z jiné planety, tak musí nejdřív prorazit flotilou. Dvě nepřátelské flotily na orbitě na sebe zaútočí až po příkazu jednoho z majitelů. V bitvě zase bude bonus od ostatních plavidel vlastního rodu a aliance. 
Pokud útočím ze svého léna na jiné na stejné planetě, s flotilou bojovat nemusím, ale flotila dává bonus jednotkám.
ten obranný bonus (i skrz alianci) tam určitě musí být.
k otázce zabrání celé planety jedním rodem. To určitě není na škodu. Ba naopak to bude podporováno, protože pokud rod objeví planetu, tak ta bude sice vidět v kartografii, ale první dva dny ji budou moct osidlovat pouze příslušníci daného rodu. Takže to nejspíš budu šílené akce, kdy vedení objeví planetu a houfně se tam nahrnou hráči aby pozabírali léna a nenechali jediné volné, protože to bude potencionální předmostí... 
Léna půjdou i předávat (pochopitelně za daň Impériu) mezi hráči (pouze svého rodu??? aliance???).

**Comment by minohimself** [comment]
je tam pridana linearna zavislost na poscte len je to v globals "od poctu"
