### ISSUE TITLE
Bug: prihlaseni

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#142]
zdarec.. jsme s mOBEM asi prvni multaci.. takze vysvetlim situaci...
1. kancl. jedna IP 3x PC 
2. ja se prihlasit muzu uplne normal.. mOB nemuze. nemuze ani z domu nemuze nikde¨
PROSIM O RESENI

http://beta.dunaonline.cz/topics/264

**Comment by minohimself** [comment]
??? este stale ?
