### ISSUE TITLE
Navrh: cena presunu populace

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#145]
Presun populace stoji stejne jako presun materialu. Ale populace je neumerne vice. 
Navrh: Castku za presun populace delit 50/100/200, aby to melo nejakou vypovedni hodnotu.
Presun stoji stejne at je to meziplanetarni nebo po planete. Mezi planetami to bude urcite drazsi nez po planete. 
Navrh: Do castky brat v potaz vzdalenost na jakou se presouva. Po planete nejlevnejsi(koef 0.7),Sousedni kvadranty(koef 1) a dal bych to pocital podle vzdalenosti cilove a zdrojove planety

**Comment by Tar-Gilkaltar** [comment]
Kvadranty by se složité počítali. Navíc díky gilde to není potřeba. Při jejich přepravě šlo o množství a nikoliv o vzdálenost. :)

**Comment by minohimself** [comment]
zmenil som presun popky da sa teraz nastavit cez globals osobitne na pl/lene
