### ISSUE TITLE
Správa - Vojensky mentat a posíláni surovin

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#149]
Vojensky mentat smí posílat suroviny, což by neměl.

**Comment by minohimself** [comment]
jsi si jist ?

**Comment by Alenil** [comment]
Jo, muze to. Ted otestovano

**Comment by minohimself** [comment]
schoval som pre ostatnych tlacitko poslat, ale to je zname ze sa da dostat do spravy naroda aj ked by si nemal mat prava ?

**Comment by Alenil** [comment]
vojensky mentat tam muze pres nabidku v menu.
obyc hrac tam musi pres odkaz, ale kdyz odkaz ma tam tam muze delat co chce

2013/12/25 mino notifications@github.com

> schoval som pre ostatnych tlacitko poslat, ale to je zname ze sa da dostat
> do spravy naroda aj ked by si nemal mat prava ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/149#issuecomment-31205882
> .

## 

A ka¾dého padlého andìla laskavì pozvednìte, a né ¾e do nìj je¹tì
kopnete,anebo ze strachu pøed ním uteèete

**Comment by minohimself** [comment]
jou prerobime prava

**Comment by janpadrta** [comment]
testuj v akci posílání surovin, jestli má potřebnou hodnost a jestli patří do potřebného národa. If - else - end to jistí...

je to přesné a učinné... na úrovni controlleru už to nejde zfalšovat nějakou upravenou url
