### ISSUE TITLE
Bug: chyba v přepočtu melanže

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#152]
řádek 119:
melange = leno.vynos('melange') \* (user_tech + house_tech) \* nahoda_produkce

by měl vypadat takto:
melange = leno.vynos('melange') \* user_tech \* house_tech \* nahoda_produkce

**Comment by minohimself** [comment]
preco si myslis ze tam je chyba ? ak mislis co hlasili tie male zisky to bola moja vina narodny vyskum bol 0. miesto 1.

**Comment by Doktoros** [comment]
Právě že jsou dvojnásobné zisky melanže. 1.02 za národní plus 1.02 za vlastní to dá 2.04 bonus

**Comment by minohimself** [comment]
to uz opravujem kein stress
