### ISSUE TITLE
Navrh: posuvnik u vyctu len

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#157]
U zastavby len, pod menu kde si vybirame leno by to chtelo posuvnik, jelikoz od vetsiho poctu len by se cely sloupec na obrazovku nemusel vlest :-)

http://beta.dunaonline.cz/topics/320

**Comment by Tar-Gilkaltar** [comment]
No posune se to s celou stránkou. Nikdy jsem to nezkoušel s vice jak 30 Leny.

**Comment by minohimself** [comment]
urobime s sass alebo tam dame jquery autocomplete
