### ISSUE TITLE
Navrh: Zastavenost/ souhrne informace o lenech

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#158]
Nevim jestli to nekde je [Seznam vasich len?], ale zatim jsem nikde nenasel nejakou "tabulku" ktera by mi jasne rekla, na jakem lenu mam kolik surovin. Pri vetsim poctu len je celkem na dlouho proklikavat vsechny lena a hledat kazdy kilogram materialu. Hodil by se nejaky prehled o tom, at vim odkud kam muzu poslat :-)

A rovnou by se hodila v seznamu i informace o zastavenosti lena

http://beta.dunaonline.cz/topics/321

**Comment by janpadrta** [comment]
asi nějaké nové view. ale to jsi už dělal, ne?

**Comment by minohimself** [comment]
nie iba cisto zoznam len nie, ale spravim ;)
