### ISSUE TITLE
Otazka: Poslanci

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#160]
Dovolba poslancu diky vetsimu vlivu v imperiu se deje take az v nedeli nebo je to automaticke hned kazdy prepocet?
on totiz Vernio maji vic poslancu, min hracu, min planet a mensi vliv ...

---

Zajímavé je, že v "Zasedání Landsraadu" jsem napočítal 47 poslanců, ale v té grafické úpravě nalevo, je jen 38 políček :D

http://beta.dunaonline.cz/topics/326

**Comment by Tar-Gilkaltar** [comment]
Grafika není funkční.
Pokud není poslanec v rodě zvolen ma rod smůlu. Nemají V stavět jen města :)))
