### ISSUE TITLE
Bug: nesrovnalost v cenach budov

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#167]
Stavel jsem "Hlubinná těžba (3)", cenu mam ukazanou jako Sol 270.85, Materiál 259.08 
Ale platil jsem Sol 288.85,Mat 275.88 
Muj vyzkum do infrastruktury mam na max, narodni je na 3. 

Zkousel jsem to na druhym uctu kde je jen narodni lvl 3, osoni 0. 
Cena se ukazuje o 3%nizsí, ale bere to jako by narodni vyzkum nebyl

http://beta.dunaonline.cz/topics/349

**Comment by Tar-Gilkaltar** [comment]
Mino, je zapocitan do produkce vliv národního výzkumu? Prosím o kontrolu.

**Comment by minohimself** [comment]
to uz by melo byt hotovo
