### ISSUE TITLE
Navrh: Uplatky, posilani mely hracum mimo narod

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#170]
Je nějaká možnost odeslat suroviny jakémukoliv hráči? Kromě vlastního národa a malorodu jsem takovou možnost nenašel. Což je velká škoda, protože jak se má pak uplácet hráč?

**Comment by relmi** [comment]
http://beta.dunaonline.cz/topics/365

**Comment by Tar-Gilkaltar** [comment]
Prez trh :))
