### ISSUE TITLE
Navrh: volba imperatora

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#171]
Bylo by fajn, kdyz se vyhlasi nove volby aby byly stavajici hlasy smazane a ve volbe my meli vsichni kandidati na zacatku stejnou sanci?
Kdo obhajuje, at si hlasy sezene znovu a kdo se snazi dostat at si taky sezene hlasy.

---

Já bych uvítal, kdyby členům landsraadu někde svítilo nějaké upozornění, že probíhají volby.

http://beta.dunaonline.cz/topics/368

**Comment by Tar-Gilkaltar** [comment]
To opravil doktor pokud se nemilim. Pokud ano prosím o close.

**Comment by Tar-Gilkaltar** [comment]
Ohlašení svítí
