### ISSUE TITLE
Navrh: planety k osidleni filtr

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#175]
http://beta.dunaonline.cz/planets
Pridat filtr, kde by se mi zobrazily jen volne planety, tzn ty ktere mohu osidlovat

http://beta.dunaonline.cz/topics/376

**Comment by minohimself** [comment]
Vidis len planety na ktorych je miesto v /planets

**Comment by Alenil** [comment]
Neni pravda. Jsou videt i plne zabrany planety. V soucasnosti treba Alara VI

**Comment by minohimself** [comment]
ale bude ked simi spravi update ja uz to mam lokalne tak spravene
