### ISSUE TITLE
Bug: volby vudce

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#177]
Momentalne mame 23 hracu a volby vypadaji nasledovne: 
Geronimo - 12 
Dominik Vernio - 10 
Ozmar - 1 
Azurit - 1 
BoBricek - 1
Nejak se mi nezda ten Dominik Vernio, protoze: 
a) vubec se nepredstavil, nikdo ho nezna, aktivoval si ucet vcera 
b) je to postava z knihy

**Comment by minohimself** [comment]
pravdepodobne odisli do rene, malo by byt dobre teraz
