### ISSUE TITLE
Chyba: cena budov po vyzkumu

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#180]
Vlastni vyzkum "infrastruktury" na full, vyzkum naroda by mel byt taky full (ted nemuzu overit)

Ceny budov:

Trh (1) = 84.16 S / 105.20 M

Banka (2) = 81.00 S / 95.73 M

Burza (3) = 120.98 S / 142.02 M

Cili druha uroven budovy je levnejsi nez prvni, coz je ocividne blbost

http://beta.dunaonline.cz/topics/390

**Comment by minohimself** [comment]
no to nieje blbost vyskumu ale cien nie ?

**Comment by Alenil** [comment]
Jop cen, ale otazka zda to plati i se soucasnymi cenami. Po wipu jsou trochu jiny nez predtim, kdy to relmi psal.

**Comment by minohimself** [comment]
Jo ja by som to closol a potom to mozme otestovat
