### ISSUE TITLE
Bug: posta

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#183]
všimla jsem si, že v poště i když jsem nesmazala ani jednu zprávu, tak se mi zprávy nezařazují na druhou stranu, ale prostě zmizí a nikde se nezobrazují.
http://2i.cz/5b3485af7c

---

to ja zase mazu a nemaze to

http://beta.dunaonline.cz/topics/394

**Comment by minohimself** [comment]
mne to funguje vymazal som si aby som na jednu stranu poslal som si pravu a mal som stranu 2
