### ISSUE TITLE
Navrh: zalozky v liste

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#185]
Kdyz si namisto Chromu pustim IE9, tak v zalozkach jsou ty veci nejak stupnovane

http://2imgs.com/b6e95872a1

Mozna by nebylo spatne, aby to nejak bylo stupnovane, aby v tom byl lepsi prehled
treba:
Sprava hrace a volby

> Sprava malordu
> 
> > Prehled malorodu
> > Sprava naroda
> > Prehled naroda
> > Sprava Imperia
> > Prehled Imperia
> > 
> > > Jednani landsraadu
> > > 
> > > > Archiv landsraadu

Jakoze ja uz se v tom vyznam, ale mozna novacek v tom muze mit bordel (i kdyz tam tolik zalozek mit nebude)

**Comment by relmi** [comment]
http://beta.dunaonline.cz/topics/395

**Comment by Tar-Gilkaltar** [comment]
IE to stupňuje podle otevření/neotevření. Nijak cíleně to není.
