### ISSUE TITLE
BUG: vypocet produkce 

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#186]
Psal jsem ti z Oldy, ale ten am po loginu "We are sorry" tak pisu odsud. Pokud by to tady bylo necitelny tak je to nahrany na http://codeviewer.org/view/code:381a

Na ML je topic http://beta.dunaonline.cz/topics/217 kde Doktor postnul vypocet produkce. 
Udavany vzorec je 
"konstanta \* počet_budov \* výnos_budovy \* bonus_výzkum \* bonus_národní_výzkum \* bonus_léno \* bonus_planeta \* náhoda"
konstanta = 1 (pro soláry = 100) 
výnos pro lvl 1 budovu je 10 
nahoda je mezi 0,9 a 1,1
Nechal jsem si postaveny jen 1 kus od kazde zakladni budovy na DP, ktera nema zadne bonusy/malusy. Osobni vyzkum je na 0, narodni je mezi 1-3%(budu pocitat s 3%)
Vypocet pro SOL "100 \* 1 \* 10 \* 1 \* 1,03 \* 1 \* 1 \* (0,9 až 1,1) " = 1030 \* (0,9 až 1,1) 
Vypocet pro MAT "1 \* 1 \* 10 \* 1 \* 1,03 \* 1 \* 1 \* (0,9 až 1,1) " 10,3 \* (0,9 až 1,1) 
Vypocet pro XPs "1 \* 1 \* 10 \* 1 \* 1,03 \* 1 \* 1 \* (0,9 až 1,1) " 10,3 \* (0,9 až 1,1) 
Vypocet pro POP "1 \* 1 \* 10 \* 1 \* 1,03 \* 1 \* 1 \* (0,9 až 1,1) " 10 \* (0,9 až 1,1) 
Vypocet pro DIL "1 \* 1 \* 10 \* 1 \* 1,03 \* 1 \* 1 \* (0,9 až 1,1) " 10 \* (0,9 až 1,1)

Skutecnost SOL = 281 
Skutecnost MAT = 100 
Skutecnost XPs = 11 
Skutecnost POP = 22660 
Skutecnost DIL = zapomel jsem postavit tovarnu :D

Imho spravne hodnoty promennych 
SOL koeficient = 28 
MAT koeficient = 10 
XPs koeficient = 1 
POP koeficient = 2200 
DIL koeficient = 0,1 nebo výnos_budovy = 1

**Comment by minohimself** [comment]
si si isty ? podla mna je to ok

**Comment by janpadrta** [comment]
Toto jsem nepsal já, to jsem jen postnul co napsali na syselaadu... očividně to tu produkci počítá nějak divně...

**Comment by minohimself** [comment]
To boli katastrofy a podobne

**Comment by Alenil** [comment]
To je stara vec, ted uz produkce popiskum vicemene odpovida. Az na trh, kde popisek rika 10, realita 1000

**Comment by minohimself** [comment]
njn to je kozmetika

2014/1/6 Alenil notifications@github.com
