### ISSUE TITLE
Chyba: Udalost na planete po startu veku

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#191]
Hned po startu veku/hry mame na Grummanu Asteroid. Asi by bylo fajn mit aspon den na rozkoukani nez nas neco zabije :)

**Comment by Tar-Gilkaltar** [comment]
Mino. Dej tam odklad 3 propočty na jakoukoliv událost prosím. :)

Zkratka az po 3. Přepočtu se začnou objevovat události.

**Comment by minohimself** [comment]
Hotovo
