### ISSUE TITLE
Navrh: hlas na vudce po registraci

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#195]
Slo by udelat, aby pri vstupu/regnuti do naroda nebyl hlas pro sebe? Ted je u nas hrozne moc "aktivnich" lidi a kazdy ma 1 svuj hlas.
http://beta.dunaonline.cz/topics/31

**Comment by Tar-Gilkaltar** [comment]
Takto ba druhou stranu vidíš, kdo ještě nehlasoval :)
