### ISSUE TITLE
Chyba: vudce poslancem

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#199]
Vudce se automaticky stava poslancem, ale kdyz o Vudcovstvi prijde tak poslancem zustava dal. Nevim, jestli to stejnebude fungovat i po volbach Poslancu, ale teoreticky stihnem do voleb mit vsechny cleny rodu v Landsraadu :)
http://beta.dunaonline.cz/topics/37

**Comment by Tar-Gilkaltar** [comment]
Vůdce již není automaticky poslancem. Tedy vyřešeno :)))
