### ISSUE TITLE
Ukazatel skladované melanže na planetě

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#20]
http://beta.dunaonline.cz/fields/2

Prosím přidej ukazatel množství uložené melanže na celé planetě.

V levém sloupci v položce Na planetě

Podobná věc by se měla zobrazovat v informacích o planetach v http://beta.dunaonline.cz/fields

Děkuji

**Comment by minohimself** [comment]
Melange je u usera nieje skladovana na planete.
