### ISSUE TITLE
[chyba] Opravneni

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#203]
Pres link se da dostat na jakoukoli stranku, i takovou kam nemam mit pristup. Tyn jako normalni hrac muzu do Spravy naroda, Spravy Imperia atd a provadet akce jako bych opravneni mel.

**Comment by Alenil** [comment]
Opravneni do IS pres http://beta.dunaonline.cz/sprava_imperia opravil GIlbert - http://beta.dunaonline.cz/topics/289#

**Comment by janpadrta** [comment]
normálně bych do všech metod přidal if - else - end test, jestli mám právo na tuto akci... kašleme na cancan... někde funguje, někde ne... je to složitější, ale přesné. Do modelu User udělej metody, které budou vracet true/false jestli má na nějakou akci právo... už jsem to začal s náhledem do syselaadů, tak podle toho.
