### ISSUE TITLE
[chyba] Udalosti

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#205]
1. Vypada to ze udalosti nic nedelaji(nijak se neprojevuji v % Seznamu vasich len)
2. Pokud je udalost na PLANETE tak neni videt kdo ji muze odstranit.
3. na DP je to vudce, ale na ostatnich?
4. Pokud je udalost na PLANETE kde mam nekolik LEN, tak v seznamu udalosti se zobrazuje pro kazde LENO zvlast.
5. Z popisu neni poznat co ktera udalost dela

**Comment by minohimself** [comment]
3ka je hotovo,
4ka pokial tam nieje leader tak nikto ( treba vymysliet)

**Comment by Alenil** [comment]
1. Kazdy si zaplati pomernou cast podle toho kolik ma tam len? A cenu udalosti upravit podle maximalniho poctu len
   Pr1: planeta 20 len max. Ja mam 4, kolega 8. Celkova cena udalosti 20000,  ja zaplatim 4k, on 8k
   Pr2: planeta 65 len, mam 15, kolega 1, Celkova cena 65K, zaplatim 15K, on 1K

**Comment by minohimself** [comment]
Tak mne to je vpodstate jedno, ako sa rozhodnu chalani tak bude ;)

**Comment by Doktoros** [comment]
události z planet by měl odstraňovat majoritní rod.
Platí filozofie, že události na lénu odstraňují hráči, události na planetě odstraňují rody.

čili buď to bude moct udělat někdo z vedení dominantního národa, nebo vedení každého rodu, který ma na planetě léno.

ALE!!! pokud to někdo odstraní, tak zaplatí ten rod CELOU částku! pokud se dohodnou na spolupráci, je to fuk, ale to už je na nich...

**Comment by Alenil** [comment]
Muze planetarni udalost odstranit mentat? Pokud ne, slo by to pridat? Aby
se nestalo, ze vudce bude jeden den na dovoleny, nebude mit moznost lognout
a neco desnyho se stane.
Mozna pridat moznost Vudci pridat neco jako Zastupce bez vyhod, jen se
stejnymi pravy jako ma Vudce, vcetne volby mentatu atd.

Dne 28. listopadu 2013 13:15 Jack notifications@github.com napsal(a):

> události z planet by měl odstraňovat majoritní rod.
> Platí filozofie, že události na lénu odstraňují hráči, události na planetě
> odstraňují rody.
> 
> čili buď to bude moct udělat někdo z vedení dominantního národa, nebo
> vedení každého rodu, který ma na planetě léno.
> 
> ALE!!! pokud to někdo odstraní, tak zaplatí ten rod CELOU částku! pokud se
> dohodnou na spolupráci, je to fuk, ale to už je na nich...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/205#issuecomment-29459744
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by Doktoros** [comment]
určitě to m usí mít možnost udělat i mentat. Od toho tu je. 

Mentat má úplně stejná práva jako vůdce, kromě jmenování mentatů :-)

**Comment by minohimself** [comment]
Takze uz len pridam prava mentatovi, a asi aj view udalosti naroda kde by bol vidiet zoznam udalosti na planetach kde ma aspon jedno leno hrac z toho rodu
