### ISSUE TITLE
[feature] Zobrazeni NS pro řadové hrace

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#208]
Stav NS vidi(a mohou s nim zaroven pracovat) jen Vudce, Mentat, ArmyMentat. Ostatni nemaji moznost zjistit stav skladu.

**Comment by minohimself** [comment]
akoze maju link ale nedostanu sa tam lebo prava ?

**Comment by Alenil** [comment]
Obycejny hrac nema ani link. Jediny co vidi je http://beta.dunaonline.cz/houses/8 ale tam neni sklad.
Funkcionar ma navic http://beta.dunaonline.cz/sprava_rod?id=8 kde je sklad videt

**Comment by minohimself** [comment]
Aha ok je to feature, no to sa dohodneme ;)

2013/11/27 Alenil notifications@github.com

**Comment by Doktoros** [comment]
Jde o to, jestli normální řadový hráč má mít možnost ten sklad vidět. Já si myslím že spíš ne. Normálnímu občanovi je jednok, kolik surovin má celý rod. On si o ně požádá a podle možností je od vedení dostane.

klromě toho ten první link vidí všichni i z jiných rodů, na ten druhý už se nikdo z jiného národa nedostane

**Comment by Alenil** [comment]
No jde o to, ze netusim zda mam zadat, kdyby ten sklad byl jen videt tak se
podivam, vidim mely 0, tak nebudu psat. Ted si napisu o melu a musi mi
nekdo odpovedet, ze zadna neni, at si napisu jindy.
A teoreticky, kdyz si da nekdo praci tak pomoci prehledu akci naroda se da
sklad spocitat.

Dne 28. listopadu 2013 13:11 Jack notifications@github.com napsal(a):

> Jde o to, jestli normální řadový hráč má mít možnost ten sklad vidět. Já
> si myslím že spíš ne. Normálnímu občanovi je jednok, kolik surovin má celý
> rod. On si o ně požádá a podle možností je od vedení dostane.
> 
> klromě toho ten první link vidí všichni i z jiných rodů, na ten druhý už
> se nikdo z jiného národa nedostane
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/208#issuecomment-29459560
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by Doktoros** [comment]
zrovna toto mi je celkem fuk, klidně to tam zobrazíme.

míň práce pro špiony :-)

**Comment by Tar-Gilkaltar** [comment]
Já jsem proti. Ve staré duně se to právě kvůli špiónům měnilo.

**Comment by minohimself** [comment]
ok dajte mi rozhodnutie a ja to spravim :dancer: 

co keby sme spravili ankety ? narodne malorodne narodne ?

**Comment by janpadrta** [comment]
NE! stav skladu vidí jen vedení a šmitec :-)
