### ISSUE TITLE
[BUG] odvolání Imperátora

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#213]
Landsraad musí mít možnost odvolat Imperátora/regenty - jedním tlačítkem se hned na první pozici zařadí zákon o důvěře. 

Pokud projde, automaticky se odvolá imperátor a vyhlásí se nové volby. Když se odvolá Imperátor, zruší se všichni vezíři i dvořané. 

Bude to systémový zákon, který bude mít pevné znění a podle toho se pozná, že je to ten zákon.

**Comment by Alenil** [comment]
Vymyslet omezeni, aby se toho nezneuzivalo. Hlasovat kazdy den o duveru
neni idealni.

Dne 28. listopadu 2013 10:54 Jack notifications@github.com napsal(a):

**Comment by Doktoros** [comment]
co třeba omezení, že po úspěšném zvolení bude imperátor týden chráněn?

pokud odvolání neprojde, tak by se dalo opakovat až po nejbližším přepočtu?

**Comment by Alenil** [comment]
Ten tyden zni dobre, ale pri neuspechu bych dal ochranu 1 den,
tzn  10. ho nesvrhnou, 11. to jeste nepujde, 12. to muzou zkusit znovu

Dne 28. listopadu 2013 13:04 Jack notifications@github.com napsal(a):

> co třeba omezení, že po úspěšném zvolení bude imperátor týden chráněn?
> 
> pokud odvolání neprojde, tak by se dalo opakovat až po nejbližším přepočtu?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/213#issuecomment-29459226
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by Doktoros** [comment]
jo to by šlo, prostě jeden den by byl klid.

**Comment by minohimself** [comment]
Ok takze ja to takto spravim :P

**Comment by minohimself** [comment]
ok je to ako normalny zakon hlasuje sa o nom 2 dni takze nebude ziadna ochrana ale proste jeden pokus trva dva dni ;)
