### ISSUE TITLE
[BUG] odvolání Správce Arrakis

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#215]
Imperátor musí mít pravomoc jmenovat a odvolat Správce Arrakis

jedním tlačítkem odvolá, jedním tlačítkem a comboboxem (všichni hráči z hratelných rodů) jmenuje.

pokud je Správce odvolán, tak se to projeví hned, ale zároveň se do globals zapíše do již existujícho bezvladi_arrakis. O prvním přepočtu se produkce vypočte jako by tam nikdo nebyl (myslím jen 10% melanže se vytěží, to by mělo fungovat). Pokud se hned po odvolání někdo dosadí, tak se to stejně vypočte jakoby tam nikdo nebyl, ale hned po výnosu arrakis, se toto glabls přepne na false, okud už správce je jmenován. Prostě jeden přepočet bude hodně nízkej výnos.

**Comment by minohimself** [comment]
a teraz sa to ako spravilo ?

**Comment by janpadrta** [comment]
dělal jsem to ručně v db a produkce se neřešila.

**Comment by minohimself** [comment]
Este otazka, ked nastavim ten datum alebo aky to je typ, ako bezvladi uz je metoda v prepocte ktora to setne na false ?
