### ISSUE TITLE
[BUG] nová funkce Předseda Landsraadu

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#216]
je potřeba udělat novou funkci - Předseda landsraadu (jen sloupeček u Usera - chairman). 

tato bude volená stejně jako imperátor (použít úplně stejný systém) a bude mít možnost posouvat zákony a přednostně ukončovat jejich volbu (označí zákon a ten se o přepočtu ihned vyhodnotí.

předsedovi se budou ukazovat šipečky u zákonů v čekací frontě a bude jim moc měnit order v tabulce, čímž se budou posouvat nahoru a dolů. 

U zákona v hlasování bude mít tlačítko, kterým umožní jeho okamžité vyhodnocení o nejbližším přepočtu (asi přidat sloupeček oznaceno_k_vyhodnoceni)

**Comment by Alenil** [comment]
Spravce bych nevolil, ale automaticky by jim byl druhy v poradi z volby
Imperatora. Da se predpokladat, ze to bude jeho nejsilnejsi protikandidat.
Pokujd by byli 2 a vice lidi se stejnym poctem hlasu tak by volby
pokracovaly, s tim, ze hlasy pro Imperatora by nesly zmenit.

Dne 28. listopadu 2013 11:02 Jack notifications@github.com napsal(a):

**Comment by Doktoros** [comment]
No problém je ten, že Imperátorem může být zvolen kdokoli, ale předsedou landsraadu pouze někdo z poslanců. Aspoň teda tak se mi to jeví logické. Rozhodně bych nechtěl kandidáty na Imperátora volit jen z poslanců. 

kromě toho, to jsou na sobě zcela nezávislé věci, Předseda se bude měnit každý týden (po volbách do landsraadu, která bych dal aspoň na dva týdny do budoucna), ale Imperátor může zůstat celý věk.

**Comment by Alenil** [comment]
Taky pravda. Jaka bude podminka jeho zvoleni? U impa je to 60% poslancu, u
predsedy stejne? nebo bude stacit min? Bude Imp a Spravce vyjmut z volby
Predsedy? Aby Imp nebyl poslanec a zaroven ho zvolili predsedou.

Dne 28. listopadu 2013 13:08 Jack notifications@github.com napsal(a):

> No problém je ten, že Imperátorem může být zvolen kdokoli, ale předsedou
> landsraadu pouze někdo z poslanců. Aspoň teda tak se mi to jeví logické.
> Rozhodně bych nechtěl kandidáty na Imperátora volit jen z poslanců.
> 
> kromě toho, to jsou na sobě zcela nezávislé věci, Předseda se bude měnit
> každý týden (po volbách do landsraadu, která bych dal aspoň na dva týdny do
> budoucna), ale Imperátor může zůstat celý věk.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/216#issuecomment-29459438
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by Doktoros** [comment]
U předsedy bych to asi nechal stejně, nebo snížil na nadpoloviční většinu, čili 51%.

Obecně Imp ani Správce poslanci být nemusí. Pokud ale bude jeden z nich poslancem, tak bych ho určitě z volby nevyjímal. Pokud si to poslanci tak domluví, tak se holt děj vůle Šaj-Hulúdova...

rozhodně bych to nezakazoval systémově. Když prostě bude silnej Imperátor, tak může mít pod palcem celé impérium... ale to si nemyslím, že by landsraad někdy dopustil...
Ale je to na diskuzi...

**Comment by Tar-Gilkaltar** [comment]
To okamžitě vyhodnocení se mi moc nezamlouvá. Da se to zmanipulovat v něčí prospěch. 

Zákon se mi nelíbí. Tak ho odkliknu před prepoctem a mam pokoj.

**Comment by Tar-Gilkaltar** [comment]
A přidal bych moderátora landsraadniho syslu.
