### ISSUE TITLE
[BUG] přehled zákonů

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#217]
U zákonů, které jsou v hlasování, musí být vidět, kdy byly zařazeny a kdy se budou vyhodnocovat.

A asi i počet poslanců, kteří odhlasovali.

Normálním hráčům se nesmí zobrazovat výsledky hlasování! to musí být tajné až do ukončení hlasování.

**Comment by janpadrta** [comment]
jen upravit view, aby ukazovaly, co ukazovat mají...
