### ISSUE TITLE
[BUG] vůdce poslancem

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#218]
vůdce se nesmí automaticky stávat poslancem. Poslancem se stane jen a pouze ten, koho zvolí hráči ve volbách. Vůdci, mentati, vezíři Imp/Reg, budou mít přístup do landsraadního syselaadu i do jednání landsraadu, ale nebudou moct hlasovat o zákonech.

ALE můžou je předkládat.

Když někdo z nich bude i poslancem, tak samozřejmě hlasovat může...

**Comment by minohimself** [comment]
toto asi niekde riesime ze dostane hned poslanca, a moze byt aj aj a ? resp ked je poslancom a zvolia ho za vodcu ?

**Comment by Doktoros** [comment]
když ho zvolí poslancem i leadrem, bude obojí. pokud ho zvolí jen vůdcem, tak poslancem není
