### ISSUE TITLE
[bug] Vyzkum - Investice do koreni

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#219]
1. Osobni vyzkum nakup LENA zdrazuje
   Chybny vzorec je "cena \* ( 1 + 0,02 \* lvl )" misto spravneho "cena \* ( 1 - 0,02 \* lvl )" 
2. Narodni vyzkum jen zvysuje produkci koreni. bug nebo umysl?

**Comment by minohimself** [comment]
1 hotovo 
2. asi hej :D
