### ISSUE TITLE
[issue] Tovarny na Arrakis

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#220]
Tovarny na Arrakis jsou za prve levne a za druhe chybi nejaky strop. V soucasnosti je obrovsky prisun mely do Imperia.
Bug: V akcich Imperia se ukazuje nakup harvesteru, ale vsude jinde se pise o tovarnach.
Navrh: Nad urcity pocet harvesteru/tovaren snizovat prumerny zisk jedne tovarny
Tzn: 1-10 tovaren: kazda zisk 100mg
 11-15 tovaren: kazda zisk 99mg
atd
podle toho kolik % bude snizeni se da nastavit strop na pocet tovaren, kdy se nevyplati stavet dalsi

**Comment by janpadrta** [comment]
Továren se v současné době dá postavit jen 19 (+ arrakén je to 20 budov jako na každém jiném léně)
v budoucny budou horní hranici omezovat fremeni, kteřým poroste aagrsivita s počtem harvesterů a budou je ničit.

**Comment by Alenil** [comment]
jen 19? Proto jich tam je ted 104?

Dne 29. listopadu 2013 23:07 janpadrta notifications@github.com napsal(a):

> Továren se v současné době dá postavit jen 19 (+ arrakén je to 20 budov
> jako na každém jiném léně)
> v budoucny budou horní hranici omezovat fremeni, kteřým poroste aagrsivita
> s počtem harvesterů a budou je ničit.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/220#issuecomment-29539366
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by janpadrta** [comment]
19 jich může postavit správce. Zbytek jsem dělal já ručně.
Taky je nutno myslet na to, že v současné době je produkce dvojnásobná. je to bug a už je opraven.

asi začnu dělat na fremenech kteří se vzrůstajícím počtem továren budou agresivnější a budou továrny bořit... tím se horní hranice bude udržovat sama...

**Comment by minohimself** [comment]
tak to mozme closnut ?

**Comment by Doktoros** [comment]
jj, toto se vyřeší fremenama.
