### ISSUE TITLE
[bug/feature] Udalost - Meteorický roj

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#221]
Meteorický roj ZDVOJNASOBUJE produkci materialu.
Pokud je to umysl, tak bych pridal moznost ostatnim rodum rusit planetarni udalosti jinych rodu - spojenci by si mohli rusit udalosti, popr jako gesto dobre vule.
Mozna pridat moznost zpusobit udalost na cizi dp? Cenu nastavit podle poctu hracu, aby vetsi bohatsi narody platily vic, a cena za odstraneni byla pri stejnem poctu hracu nizsi. Byla by to dalsi moznost vedeni ekonomickeho boje

**Comment by minohimself** [comment]
to by sa nemalo uz diat, a uz mozes rusit len svojho naroda udalosti
