### ISSUE TITLE
[feature] Fremeni

### ISSUE THREAD

**Issue by janpadrta** [DunaOnline/game#222]
- agresivita fremenů roste s počtem přidaných továren
- o přepočtu před výnosem se otestuje, jestli fremeni nezaútočí
- pokud jo, zničí část továren (možná přesně tolik, kolik je agresivita
- fremeni jdou uplatit, aby agresivita klesla - tajně
- fremeni jdou uplatit, aby se agrese zvedla - tajně
- fremeni udržují vztahy s národy, kteří se je pokusili uplatit, čím lepší vztahy, tím větší vliv budoucího uplacení. Sloupeček u národa
- Impérium může taky uplácet fremeny

**Comment by Tar-Gilkaltar** [comment]
To jsme plánovali od počátku ne? :)

**Comment by Doktoros** [comment]
Jj, plánovali. Já to jen shrnul a udělal :-)

**Comment by Tar-Gilkaltar** [comment]
Fine ;) podplácení bych dal primo do správy Arrakis vudcum, imperatorovi, správci a vezirum. Nebo bys TP chtěl dat všem?
