### ISSUE TITLE
[bug] Sprava hrace a volby

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#224]
Ve "Sprava hrace a volby" je v tabulce hlasovani videt jen 5 mist pro koho se hlasuje(vudce, senator,general) , ale hlas muze mit vic lidi coz dosti omezuje moznost vyberu koho volit.
Chtelo by to tam zobrazovat vsechny kdo ma nejaky hlas. U toho vudce a gene to asi neni tak dulezity ale Hlasy pro Senatory byvaji dost vyrovnany.
++ Zvyraznit ty, ktery budou pri soucasnem stavu vlivu zvoleni

**Comment by minohimself** [comment]
Toto nieje bug bolo to tak mysleno

**Comment by Alenil** [comment]
Takze i kdyz ma narod narok na 10 nebo klidne vic senatoru tak bude videt jen 5? Bez moznosti zjistit jestli ma dostatecny pocet lidi hlas, aby zadne senatorske kreslo nepropadlo?
Ta kombinace 
-- nemam dost lidi s hlasem pro senatora = prijdu o mista v Landsraadu 
a 
-- nevidim kolik lidi ma hlas pro senatora
mi nedava smysl.

**Comment by Tar-Gilkaltar** [comment]
Co přidat možnost náhledu na všechny hlasy a Top5 zachovat?

**Comment by minohimself** [comment]
spravil som to tak ze ked pojdes miskou na aktualne poradie vipise ti hlasy
