### ISSUE TITLE
[feature] dynamicky generovane planety

### ISSUE THREAD

**Issue by z0ny** [DunaOnline/game#225]
Proc?
- kazda planeta by byla vice mene unikatni
- zajimave extremy (vysvetlim nize), coz by obcas vedlo k velkemu zajmu pripadne absolutnimu nezajmu k planete
- nebylo by to tak predvidatelne a planovatelne jak ted (je myslim 6 typu planet nepocitam li velikost, tudiz muzu predvidat co kam budu stavet abych mel co nejvetsi zisk, s dynamicky generovanyma planetama nevim nic)

Jak?
- hodnoty by se vygenerovaly pred vytvorenim planety
- kazda planeta by mela napr (+50% \* pocet_typu_bonusu) a (-50% \* pocet_typu_bonusu), takze momentalne by to bylo +300% a -300% (population_bonus, pop_limit_bonus, material_bonus, solar_bonus, exp_bonus, fields)
- tento zaporny a kladny bonus by se nahodne rozdelil mezi jednotlivy staty tak, aby zadny znich nemohl presahnout 100%
- vysledny kladny i zaporny hodnoty by se od sebe odecetli a aplikovali specifikovanou hodnotu danyho typu (konstantu)
- viz kod dole

Problemy
- vsechny bonusy bude potreba preves z tabulky planet_types do planets, protoze se tykaji planet a ne typu planet, v typech planet zustane pouze nazev a rozmezi podle ktereho se ridit (pocet len, populace)

Vyhody
- psal jsem to uz vys, unikatni planety s moznosti vysokych kladnych/zapornych bonusu a ruznym pocem len

Nemam problem to napsat az si nekdy rozjedu vyvojovy prostredi duny ve widlich

ukazka kodu, mel by byt funkcni v konzoli, hodnoty jsou samozrejme zatim nacrt

```
class Planet < ActiveRecord::Base
  class Bonus
    # definice maxim jednotlivych bonusu
    POPULATION = 100
    POPULATION_LIMIT = 10
    MATERIAL = 10
    SOLAR = 10
    EXPERIENCE = 10
    FIELDS = 80

    # definice co k cemu patri, klice jsou shodne s nazvy atributu
    TYPES = {
       population_bonus: POPULATION,
       pop_limit_bonus: POPULATION_LIMIT, 
       material_bonus: MATERIAL, 
       solar_bonus: SOLAR, 
       exp_bonus: EXPERIENCE,
       fields: FIELDS
    }

    # kolik pridat do celku za kazdy typ bonusu (0.5 = 50%), takze v tomto zneni je k dispozici zaporneho a kladneho 300% bonusu
    PER_TYPE = 0.5

    # maximalni hodnota bonusu na typ bonusu (napr populace nemuze mit vetsi bonus nez 100% pokud nastavime 1)
    MAX_PER_TYPE = 1.0
    MIN_PER_TYPE = 1.0
  end

  def create
    # naklonuju si template a nad nim budu pracovat
    bonuses = Bonus::TYPES.clone
    # soucty pozitivnich a negativnich nahodnych cisel pro pomerovy rozdeleni celku
    negative, positive = 0, 0
    # nejprve vygenerujeme nahodna cisla pro kazdy typ bonusu v negativu a positivu
    bonuses.each { |k, v| 
      bonuses[k] = [n = rand(100), p = rand(100)]
      negative += n
      positive += p
    }.each { |k, v| 
      # vypocitame pomerove procenta pro kazdou polozku jak zaporna tak kladna (pokud by nahodnou vsechna vysla 0 obejdeme deleni nulou)
      n_percent = (negative == 0 ? 0 : (v[0].to_f / negative.to_f) * (Bonus::TYPES.keys.length * Bonus::PER_TYPE))
      p_percent = (positive == 0 ? 0 : (v[1].to_f / positive.to_f) * (Bonus::TYPES.keys.length * Bonus::PER_TYPE))
      # zjistime jestli hodnota bonusu neprevysuje maximalni povolenou hodnotu a pokud ano nastavime ji na maximum a nasledne zapornou odecteme od kladne
      bonus = (p_percent > Bonus::MAX_PER_TYPE ? Bonus::MAX_PER_TYPE : p_percent) - (n_percent > Bonus::MIN_PER_TYPE ? Bonus::MIN_PER_TYPE : n_percent)
      # procenta bonusu prevedeme na realne hodnoty bonusu definovane v konstantach a prevedeme na procentualni hodnotu
      # mozna by nebylo od veci to prevest na int, protoze napriklad lena jsou jen cela cisla, da se poresit prepisem metody, viz. nize
      bonuses[k] = ((Bonus::TYPES[k] / 100.0) * bonus * 100.0).round
    }

    # vytvorime planetu
    Planet.new(bonuses.merge{ostatni_atributy_planety})
  end

  # zabranime vytvoreni planety se zapornym poctem len
  def fields=(size)
    self[:fields] = (size == 0 ? 1 : size.abs)
  end
end
```

Tak co si o tom myslite? Snad je to aspon trochu pochopitelny :)

EDIT: pridal jsem tam round na vysledky, mit to jako float je dle me zbytecnost

**Comment by Alenil** [comment]
Urcite lepsi jak soucasny system. Otazka jestli neni 0,5 moc. Jestli to
dobre chapu muze vyjit 3x +100 a 3x -100.

Dne 4. prosince 2013 17:50 Jan notifications@github.com napsal(a):

**Comment by z0ny** [comment]
jako nejvyssi extrem ano, nicmene i tech 100 muzes ovlivnit tim MAX_PER_TYPE/MIN_PER_TYPE, ale kdyz si to zkusis v konzoli, malo kdy ti vyjde neco, co by bylo nejak extremne vyhodne. Tezko rict, to by se poznalo az po ozkouseni

malej testik

```
30.times { puts Xxx.create.inspect }
{:solar_bonus=>-3, :exp_bonus=>2, :fields=>4, :population_bonus=>-13, :pop_limit_bonus=>2, :material_bonus=>-5}
{:solar_bonus=>3, :exp_bonus=>-1, :fields=>2, :population_bonus=>14, :pop_limit_bonus=>-3, :material_bonus=>0}
{:solar_bonus=>-5, :exp_bonus=>-1, :fields=>8, :population_bonus=>22, :pop_limit_bonus=>2, :material_bonus=>2}
{:solar_bonus=>5, :exp_bonus=>3, :fields=>44, :population_bonus=>-7, :pop_limit_bonus=>-4, :material_bonus=>3}
{:solar_bonus=>-3, :exp_bonus=>-1, :fields=>5, :population_bonus=>-3, :pop_limit_bonus=>0, :material_bonus=>5}
{:solar_bonus=>-4, :exp_bonus=>1, :fields=>40, :population_bonus=>52, :pop_limit_bonus=>2, :material_bonus=>1}
{:solar_bonus=>-7, :exp_bonus=>3, :fields=>36, :population_bonus=>-50, :pop_limit_bonus=>-2, :material_bonus=>7}
{:solar_bonus=>3, :exp_bonus=>-2, :fields=>16, :population_bonus=>19, :pop_limit_bonus=>2, :material_bonus=>-2}
{:solar_bonus=>-1, :exp_bonus=>-5, :fields=>26, :population_bonus=>19, :pop_limit_bonus=>6, :material_bonus=>0}
{:solar_bonus=>9, :exp_bonus=>-7, :fields=>52, :population_bonus=>-26, :pop_limit_bonus=>6, :material_bonus=>1}
{:solar_bonus=>3, :exp_bonus=>8, :fields=>34, :population_bonus=>-80, :pop_limit_bonus=>-2, :material_bonus=>-2}
{:solar_bonus=>2, :exp_bonus=>0, :fields=>15, :population_bonus=>21, :pop_limit_bonus=>-4, :material_bonus=>-2}
{:solar_bonus=>-3, :exp_bonus=>1, :fields=>4, :population_bonus=>-55, :pop_limit_bonus=>3, :material_bonus=>5}
{:solar_bonus=>9, :exp_bonus=>2, :fields=>1, :population_bonus=>-20, :pop_limit_bonus=>-1, :material_bonus=>-9}
{:solar_bonus=>-1, :exp_bonus=>-1, :fields=>39, :population_bonus=>-62, :pop_limit_bonus=>-5, :material_bonus=>8}
{:solar_bonus=>5, :exp_bonus=>1, :fields=>48, :population_bonus=>58, :pop_limit_bonus=>-1, :material_bonus=>-5}
{:solar_bonus=>-8, :exp_bonus=>0, :fields=>22, :population_bonus=>29, :pop_limit_bonus=>0, :material_bonus=>3}
{:solar_bonus=>2, :exp_bonus=>0, :fields=>23, :population_bonus=>-3, :pop_limit_bonus=>-1, :material_bonus=>3}
{:solar_bonus=>-6, :exp_bonus=>5, :fields=>31, :population_bonus=>54, :pop_limit_bonus=>-10, :material_bonus=>0}
{:solar_bonus=>3, :exp_bonus=>-8, :fields=>10, :population_bonus=>24, :pop_limit_bonus=>-4, :material_bonus=>8}
{:solar_bonus=>-3, :exp_bonus=>2, :fields=>2, :population_bonus=>-21, :pop_limit_bonus=>-1, :material_bonus=>2}
{:solar_bonus=>-5, :exp_bonus=>-5, :fields=>6, :population_bonus=>60, :pop_limit_bonus=>-2, :material_bonus=>4}
{:solar_bonus=>-1, :exp_bonus=>5, :fields=>4, :population_bonus=>-42, :pop_limit_bonus=>-4, :material_bonus=>4}
{:solar_bonus=>-7, :exp_bonus=>4, :fields=>10, :population_bonus=>60, :pop_limit_bonus=>-3, :material_bonus=>0}
{:solar_bonus=>-4, :exp_bonus=>1, :fields=>47, :population_bonus=>-47, :pop_limit_bonus=>4, :material_bonus=>-1}
{:solar_bonus=>0, :exp_bonus=>7, :fields=>25, :population_bonus=>-23, :pop_limit_bonus=>-4, :material_bonus=>-4}
{:solar_bonus=>0, :exp_bonus=>-7, :fields=>28, :population_bonus=>55, :pop_limit_bonus=>-3, :material_bonus=>2}
{:solar_bonus=>-3, :exp_bonus=>6, :fields=>4, :population_bonus=>36, :pop_limit_bonus=>-2, :material_bonus=>-4}
{:solar_bonus=>10, :exp_bonus=>-5, :fields=>18, :population_bonus=>-24, :pop_limit_bonus=>4, :material_bonus=>-5}
{:solar_bonus=>3, :exp_bonus=>1, :fields=>4, :population_bonus=>24, :pop_limit_bonus=>-6, :material_bonus=>-1}
```

EDIT: pro prehlednost jsem to prevedl na cele cislo
EDIT2: pro jistotu jsem to matematicky zaokrouhlil a zajistil ze lena nemuzou byt nulova :)

**Comment by janpadrta** [comment]
já jsem pro... ;-)

...pokud to implementuješ ty sám :-D

**Comment by minohimself** [comment]
me too, ale tiez by si mohol pozriet preco rails admin failne pri planetach

2013/12/4 janpadrta notifications@github.com

**Comment by z0ny** [comment]
nevim cj rails admin, google rika ze webovy pristup do db :) Nic o nem zatim nevim, nemam zadne informace a prej se tam ani endostanu :)

Kazdopadne ja nemam jeste ani prostredi pro tento duna projekt. Jak rikal Honza (doktor), tak momentalne nemam ani cas, ani moc chut, od zacatku roku jsem bez zamestnani, takze tam snad uz bude chut :)

**Comment by Tar-Gilkaltar** [comment]
Také nejsem proti ale výkyv bych viděl maximálně -10% az +10% čistého bonusu.

Jména planet jsou již dana a v rezervě jich je mnoho. :)

**Comment by z0ny** [comment]
vykyv u populace dava smysl mit -100% az 100 %, predstavuju si to tak (nevim jak to ma realne byt), ze dejme tomu mesto ma kapacitu 100k lidi, kdyz ho postavis bude, tak ma 10k na startu. pokud ma planeta 0% bonus do populace tak po prepoctu tam bude stale 10k lidi, pokud ma -50% tak po prepoctu tam bude 5k lidi a po dalsim prepoctu 2.5k, pokud ma +50% bude tam 15k lidi. Specialni priklad je pokud planeta bude mit -100% :) to pak vsichni po prepoctu umrou a jediny jak tam lidi udrzet met vyzkum v nejakym bonusu na populaci a vsechno dovazet z jinych planet. Coz me pripomina ze by se mel udelat nejakej planovac pro uzivatele co si nastavi ze se ma automaticky po prepoctu samo prevest napr, planeta1-leno1 => material => planeta2-leno50 => 2500kg, nekde by si to clovek nastavil a ono by se to tam samo po prepoctu posilalo, je to jen takovy napad :)
Jinak se omlouvam, ale pres prosinec bnudu spis neaktivni rikal jsem to i Doktorovi v praci

**Comment by Tar-Gilkaltar** [comment]
Jj na staré duně to bylo -50% az 50% a to se zda ideální :) byl bys pro toto?

**Comment by z0ny** [comment]
tak to neni jen na me, ja webovky nehraju, tudiz nemam zkusenosti a z duny znam pouze ty real time strategie od westwoodu a tuhle dunu znam asi tak 2 mesice? Jinak ja osobne jsem zastancem vetsich extremu, vznikaji pak zajimavejsi planety o ktere by byl velky zajem nebo planety ktery jsou uplne k hovnu :D Takze ptas-li se me ja bych dal vsude 50% :))) Ale vse by se muselo peclive testnout co by to generovalo :))

**Comment by Alenil** [comment]
Takze planujete predelat bonus/malus populace, ze bude ovlivnovat pocet
lidi na planete misto aby ovlivnoval produkci mest? Protoze ted to funguje
tak, ze +50% z produkce mesta 10K udela 15K, ale s populaci na planete to
nehne.
Pokud to chcete predelat tak bych pro populaci udelal -75% - +25% tim by se
zaridilo, ze planety s bonusem by byli velice lakave, a na ostatnich by
bylo nutne stavet mesta,
- Pridat pro kazdy typ budovy pocet lidi na planete, protoze soucasny
  minimalni pocet je vazany jen na leno, nezavisle na zastavbe. Idealne aby
  vyssi levely potrebovaly vic lidi.

Dne 9. prosince 2013 1:33 Jan notifications@github.com napsal(a):

> tak to neni jen na me, ja webovky nehraju, tudiz nemam zkusenosti a z duny
> znam pouze ty real time strategie od westwoodu a tuhle dunu znam asi tak 2
> mesice? Jinak ja osobne jsem zastancem vetsich extremu, vznikaji pak
> zajimavejsi planety o ktere by byl velky zajem nebo planety ktery jsou
> uplne k hovnu :D Takze ptas-li se me ja bych dal vsude 50% :))) Ale vse by
> se muselo peclive testnout co by to generovalo :))
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/225#issuecomment-30097949
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by z0ny** [comment]
1. tohle je jen moje predstava, jak si myslim ze to ma fungovat, takze z toho nedelejte hotovou vec ;)
2. spatne pochopeno... je tam populacni limit bonus (dale PLB) a populacni bonus (dale PB)
3. je v planu, kazda budova by mela mit potrebu lidi na planete, nektere budovy jako napr. laborator/tovarna by meli chtit material/solary za prepocet

jeste jednou vysvetlim... (vsechny hodnoty jsou priklad realne mohou a asi i budou jinak)
PLB momentalne nijak nefunguje protoze nefunguje ani limit na mestech. 
Pokud me to Doktor vysvetlil dobre ma to fungovat tak, ze postavis-li mesto, tak se ti na lenu zvedne limit o 100k a mesto ti da automaticky 10k lidi. Z toho plyne, ze pokud je PLB 50% tak jedno mesto ti prida ubytovani pro 150k lidi a -50% to skrouhne na 50k lidi na mesto. Doktor me rikal ze pokud mesto/leno presahne kapacitu (resp presahne se limit na lenu), tak se lidi zacnou bourit/obcansky valky/whatever a pokud vsichni ve meste umrou (to jsme neresili) melo by se tez neco stat, napriklad by mel majitel o leno prijit nebo by se mu melo neco znicit
O PB jsme se nejak nebavili resp zdalo se me, ze to neni nijak vymysleny, takze me z toho logicky vyplynulo, ze PB je porodnost/umrtnost. Tim padem, kdyz je porodnost planety 0%, tak v jeden den (prepocet) se narodi stejnej pocet lidi a stejnej pocet lidi umre, pokud je +50% a la ziva planeta (tohle by melo generovat obrazek modre/zive planety), tak se za jeden den (prepocet) narodi o 50% vic lidi nez jich umre (15k), pokud je -50% a la nehostinna planeta (melo by generovat obrazek nake mrtve planety) tak jich o 50% vic umre nez se narodi (5k), to znamena, aby tohle leno mohlo fungovat, bude potreba jej dotovat jinym lenem s kladnym bonusem

BTW mam ten pocit, ze tohle bych mel psat jinam, nekam kde jsou navrhy. Guide me!

**Comment by Tar-Gilkaltar** [comment]
Můžeš to napsat na Google Docs. Je tam pro vyhrazeny dokument. :)  O planetách - https://docs.google.com/document/d/1sKC4ekf0nbjEPlnXTbriFUGwg1060Od41fiO9p9aSaM/edit?usp=sharing
