### ISSUE TITLE
Bug: Odesilani komodit

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#226]
Pokud se hacknu do imperiálního skladu, tak je zde zajímavě nastavena kontrola odeslaných komodit.
Odesílání melanže není nijak omezeno. Jde odeslat jakékoliv i malé množství, viz: 
Rodu Harkonnen poslano 0 S 3.0e-06 mg melanze hracem Ploki_Warrior. 30.11.2013  08:30:37 
Rodu Harkonnen poslano 0 S 0.12345 mg melanze hracem Ploki_Warrior. 30.11.2013  08:27:38
Toto neplatí při odeslání solárů. Zde jdou odesílat pouze celočíselné hodnoty. Veškeré desetinné částky jsou zaokrouhleny dolů. Viz: 
nastaveno: 0.12345, odesláno 0 
nastaveno: 0.5, odesláno 0 
nastaveno: 0.99, odesláno 0 
nastaveno: 1.12345, odesláno 1 
nastaveno: 1.99, odesláno 1
Bylo by dobré všude sjednotit pravidla. Všude je myšleno posílání komodit mezi lény jednoho hráče, odesílání mezi hráčem a malorodem, hráčem a rodem a mezi rody. Co jsem si zatím všiml, tak jde kdekoliv nastavit jakoukoliv (i hodně malou, např deset nul a jedničku) částku, která se skutečně odešle. 
Doporučoval bych databázovou úpravu, aby soláry, materiál a melanž byly zaokrouhlovány na dvě desetinná místa a zkušenosti, populace a výrobky (resp. výrobky z výrobků) na celá čísla. Aplikačně je to takto již zobrazováno.
Ono totiž docela zamrzí, když se vám při odeslání komodit zobrazí např. tato hláška: 
Chybi vam 0.0002099999063648 solaru

**Comment by janpadrta** [comment]
už by to jít nemělo. prosím o potvrzení, že to nejde :-)
