### ISSUE TITLE
Bug: Vyhosteny hrac

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#229]
Hrac ktery neni v narode porad zustava v ruznych hlasovanich - na vudce,senatora atd

**Comment by Alenil** [comment]
Doplneni: I kdyz je v seznamu, tak zvolen nebyl

Dne 6. prosince 2013 9:00 relmi notifications@github.com napsal(a):

**Comment by minohimself** [comment]
To uz nieje aktualne prosim otestujte to znova ja som to opravoval

**Comment by Alenil** [comment]
Vyzkousim znovu, ale kdy to bylo opraveno?
Protoze hrac ktery byc bylhosteny 6.12. a zustal v tom seznamu je ted
senator za Rene i kdyz hlasy dostal od M, a v dobe voleb uz byl v Rene.

2013/12/6 mino notifications@github.com

> Closed #229 https://github.com/DunaOnline/game/issues/229.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/229
> .

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by minohimself** [comment]
ok ja mu beriem len status landsraad ked ide k rene neriesim asi jeho hlasy na poslanca opravim

**Comment by janpadrta** [comment]
Tady bude potřeba, aby při opuštění mu to vzalo VŠECHNY (renegát nemůže být ani imperátorem :-)) funkce a smazalo to jeho a s ním záznamy z tabulky votes.

pokud renegátuje imperátor, musí být okamžitě umožněny nové volby - v globals přepnout na true parametr "volba_imperátora" a datum voleb nastavit tak za dva až tři dny...

**Comment by Alenil** [comment]
Tak to chce npvy volby do Landsraadu pokud by bylo prilis malo Senatoru.

06.12.13, janpadrta notifications@github.com:

> Tady bude potřeba, aby při opuštění mu to vzalo VŠECHNY (renegát nemůže být
> ani imperátorem :-)) funkce a smazalo to jeho a s ním záznamy z tabulky
> votes.
> 
> pokud renegátuje imperátor, musí být okamžitě umožněny nové volby - v
> globals přepnout na true parametr "volba_imperátora" a datum voleb nastavit
> tak za dva až tři dny...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DunaOnline/game/issues/229#issuecomment-30004911

## 

A každého padlého anděla laskavě pozvedněte, a né že do něj ještě
kopnete,anebo ze strachu před ním utečete

**Comment by minohimself** [comment]
A co ked imperatora vyhostia ?

**Comment by minohimself** [comment]
Ale inak landsraad mu berieme
