### ISSUE TITLE
Chyba: Vylepšení budov

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#230]
1. V nadpisu ve slově vylepšení chybí háček nad s 
2. U slova vylepšit chybí háček nad s 
3. Vylepšení jde maximálně o 10 ... přitom max je 20
4. Nebylo by špatné, kdyby každý level vylepšení stál o něco víc ... :-)

**Comment by Tar-Gilkaltar** [comment]
Háček opraven

**Comment by minohimself** [comment]
Bude se rusit vyplesovani
