### ISSUE TITLE
Bug: 06/12 probehly 3 prepocty

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#232]
ne, že bych si stěžoval, ale mám takový pocit, že proběhlo o 2 přepočty víc :D (ergo 3)

---

Jedine, co me napada je, ze to bylo kvuli posunuti volbe senatoru, protoze ta se dela v nedeli, aby to tedy posunuli, ocitli jsme se prepoctove v nedeli :)
Edit: tedy vlastne v pondeli?

**Comment by Tar-Gilkaltar** [comment]
Protože se o to postarali dva admini. A jeden 2x
