### ISSUE TITLE
BUG - Odmítnutí zákona

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#234]
Pokud kliknu na odmítnutí zákona, potom se objeví obrazovka smrti. Předpokládám že je zde problém s Vettem. 

http://beta.dunaonline.cz/imperator_zakony

**Comment by minohimself** [comment]
ale musel som pridat novy state Odmitnout, a este signed co je field kde by podla mna malo byt booleand je datetime,
true tam ide buchnut :D ale false nezozere :P
