### ISSUE TITLE
[bug] Statistika prepoctu

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#235]
1 Sloupec poplatky nic nedela/nefunguje
2. Ve sloupci "Ve skladu" je mnozstvi materialu na posledni planete v seznamu.

**Comment by minohimself** [comment]
poplatky to sa bude riesit ked bude armada ona bude spotrebovavat veci cez prepocet a aj ine veci, a ten prepocet idem spravit

**Comment by janpadrta** [comment]
tak to prosím schovej ať to hráče furt nedeptá :-D
