### ISSUE TITLE
Bug: Vyzkum Investice do koreni

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#236]
A místo toho, aby mi to o 12% snížilo náklady na osídlení nového léna, tak mi to o 12% zdražilo..

**Comment by Alenil** [comment]
Uz reportovane - mino rikal, ze to opravil, ale nejspis jen u sebe.

2013/12/10 relmi notifications@github.com

**Comment by minohimself** [comment]
asi :D

2013/12/10 Alenil notifications@github.com

**Comment by Alenil** [comment]
Opravena je cena pouze vizualne, hra po hraci porad chce nespravnou castku
http://beta.dunaonline.cz/topics/304
