### ISSUE TITLE
[bug+Dotaz] Nedostatek melanze

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#240]
Bug - IS muze jit do minusu behem platby Gilde
Do imperialnich skladu bylo odeslano -607.0 mg melanze. 11.12.2013  23:15:49

Dotaz - Co se stane/ melo by se stat pokud se nezaplati Gilde?
1. Prestane fungovat presun mezi leny? Mezi planetami?
2. Prestane fungovat posilani do NS,MS?
3. Prestanou fungovat utoky?
4. Nebo se ke vsem presunum/utokum prida cena melanz? Aby ti kteri ji maji mohli fungovat?

**Comment by Tar-Gilkaltar** [comment]
Odpověď je 1. a 3. :)

**Comment by janpadrta** [comment]
nic z toho není implementováno. Dopíšu analýzu
