### ISSUE TITLE
[F] Informace o proběhlých akcích na Arrakis v přehledu hráče

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#245]
viz http://beta.dunaonline.cz/topics/309

Bude vhodné zapisovat stavby a přesuny z a do Arrakis ve Správě hrče -  Proběhlé akce

Bylo by to stejne jako při správě vlastních planet.

**Comment by janpadrta** [comment]
Jen zápisy do poznámek Impéria
