### ISSUE TITLE
Nástěnka - Zobrazeni editace

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#248]
Při editaci by se mel zobrazit čistý kód, který nástěnku tvoří. Tedy text i s tahy.

**Comment by Alenil** [comment]
A zapnout na nastence tagy. Ted se zobrazi text tagu misto jeho provedeni

Dne 19. prosince 2013 13:00 Tar-Gilkaltar notifications@github.comnapsal(a):

**Comment by minohimself** [comment]
to uz mam ale este nech sa zapisuje do narodneho logu kto menil nastenku
