### ISSUE TITLE
[b] Přesun populace

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#251]
http://beta.dunaonline.cz/topics/337

Prave prestal fungovat presun surovin mezi leny. Presneji jsem presouval populaci a od cca 13:03 koncim na chybe: We're sorry, but something went wrong.

No .. problemy mam jen s populaci a jen nekde :) 
Vypada to, ze nejde presouvat populaci mezi leny, ktere jsou na stejne planete. U materialu tento problem neni. Mezi leny na ruznych planetach jde populace presouvat v poradku.
Dalsi vec je, ze pri velkem mnozstvi populace to pise chybu: Nemáte dost solaru na presun. 
Presneji sem v poradku presunul 1.1M populace za 22k solaru, ale 1.2M populace uz presunout nejde, kvuli zminene chybe. Solaru mam pritom dostatek.

**Comment by minohimself** [comment]
no ono si nemal dost solarou :D niekto chybne nastavil cenu za presun populacie na 1 solar :D za jednu pop ;)
