### ISSUE TITLE
Ankety Malorodne Narodne Imperialne

### ISSUE THREAD

**Issue by minohimself** [DunaOnline/game#254]
Co vy na to ?

**Comment by Tar-Gilkaltar** [comment]
Klidně ale necpal bych to mezi nástěnky. Tech je tam az moc :/

**Comment by minohimself** [comment]
napravo pod systemko, mozme spravit easy featuru ze si mozes nastavit co budes vidiet na tvojej page resp. mozes si zrusit nastenky :P co ty na to ?
