### ISSUE TITLE
[bug] Chybi odkaz na Landsraadu

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#259]
Některým hráčům chybí v menu "Komunikace" Landsraad i když jsou Senátoři. Přes rozbalovací nabídku "Změnit syselaad" nebo pres link se tam dostanou a mohou číst i psát, chyba je tedy jen v zobrazení v menu

**Comment by janpadrta** [comment]
Opraveno. Prosím o potvrzení :)

**Comment by Alenil** [comment]
Uz i nahrano? Napr spionek ho v Menu stale nema. V menu ma pouze N, Mzl a Syst i kdyz je Senator. V "Zmenit syslaad" ma vsech 5 tzn N,Mzl,Imp(jen nahled na topicy), Lands, Syst.
Ve chvili kdy je uvnitr nejakeho topicu/vlakna tak v "Zmenit syselaad" ma to same co v Menu
