### ISSUE TITLE
[feature] Změna názvu DP

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#261]
Neměl by se název DP měnit podle toho kam hráč přijde? Sice má možnost to změnit ručně, ale DP by se asi přejmenovat neměla dát, nebo jen její část - tzn aby bylo "Grumman" + "něco". Takhle hráč mlže byt v Riches ale mit domovskou Grumman
http://beta.dunaonline.cz/topics/437

**Comment by minohimself** [comment]
ale to je len nazov fieldu nie planety

**Comment by minohimself** [comment]
Mam to spravit myslis ze to bude tak dobre ?

**Comment by Alenil** [comment]
DP bych dal pevny nazev bez moznosti zmeny. Preci jen je to leno, ktere ti bylo prideleno. A ve chvili kdy zmenis narod tak je blbost aby se tva DP porad jmenovala Caladan i kdyz jsi Harko :)
