### ISSUE TITLE
Oznámení bety na dunaonline.cz

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#27]
Asi tři zmatenci se snažili prihlasita na dunaonline.cz místo na bete. Dej pls nad přihlášení třeba "Hru testujeme na beta.dunaonline.cz"

**Comment by termoSKA** [comment]
Cau, koukam ze to mozna zas oziva, stara dobra DO:-) Myslim, ze se zname s
Tarem od Riches, nepletu se? Hral jsem tam pod nickem mites, taky chvili u
CM. Kdybyste potrebovali s necim pomoct, rad se zapojim.

**Comment by Tar-Gilkaltar** [comment]
To je dost mozne :) No ted muzes skusit jit na betu :)
