### ISSUE TITLE
[bug] Vyhosteni hrace

### ISSUE THREAD

**Issue by Alenil** [DunaOnline/game#275]
At to zkousim kdykoli tak pri pokusu o vyhosteni hrace to pise "Dosiahli jste limit na vyhosteni hracu na prepocet."
- Je tam "Dosiahli" misto "Dosáhli"

**Comment by minohimself** [comment]
ide iba o ten text ? alebo nejde vyhadzovat

**Comment by Alenil** [comment]
Nejde vyhazovat A text je spatne

2014-02-15 0:38 GMT+01:00 mino notifications@github.com:

> ide iba o ten text ? alebo nejde vyhadzovat
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/275#issuecomment-35138782
> .

## 

A ka¾dého padlého andìla laskavì pozvednìte, a né ¾e do nìj je¹tì
kopnete,anebo ze strachu pøed ním uteèete

**Comment by minohimself** [comment]
ide to inde je problem, niesi mentat ani leader

**Comment by Alenil** [comment]
Zkousel jsem to jako mentat i jako vudce a nejde to. Klidne se presun k M a
dej si mentata at si to vyzkousis.
Nebo je to chyba jen u M, stejne jako to ze nam nejde Narodni landsraad a
ostatnim jde

2014-02-16 0:34 GMT+01:00 mino notifications@github.com:

> Closed #275 https://github.com/DunaOnline/game/issues/275.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/275
> .

## 

A ka¾dého padlého andìla laskavì pozvednìte, a né ¾e do nìj je¹tì
kopnete,anebo ze strachu pøed ním uteèete

**Comment by minohimself** [comment]
Jo isiel som k vam a vykopol som typca vcera ako admin, ale to by nemalo vadit idem teda hodit este jedneho :dancer:

**Comment by Alenil** [comment]
Kdyz nemam opravneni tak to pise "Nemate opravneni." ale me se ukazuje ze
jsem dosahl limitu

2014-02-16 11:03 GMT+01:00 mino notifications@github.com:

> Jo isiel som k vam a vykopol som typca vcera ako admin, ale to by nemalo
> vadit idem teda hodit este jedneho [image: :dancer:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DunaOnline/game/issues/275#issuecomment-35181356
> .

## 

A ka¾dého padlého andìla laskavì pozvednìte, a né ¾e do nìj je¹tì
kopnete,anebo ze strachu pøed ním uteèete

**Comment by minohimself** [comment]
jop sory uz to opravujem
