### ISSUE TITLE
Viditelný počet hlasů u zákona v hlasování

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#277]
Jde vidět počet hlasů při schvalování zákona. To je nešťastná varianta. Prosím skryt a zobrazit jen az v archivu zákonů.

**Comment by Alenil** [comment]
Driv to bylo taky videt. Jen to videli obyc hraci a Senatori ne.
MInimalne pocet hlasujicich tam potreba je

Dne 21. února 2014 9:09 Tar-Gilkaltar notifications@github.com napsal(a):
