### ISSUE TITLE
Přesměrovat Menu - Správa lén - Budovy

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#3]
Přesměruj tento link na http://beta.dunaonline.cz/fields/6

hráče to hodí na DP a oni si dále vyberou jakou planetu chtějí.

**Comment by Tar-Gilkaltar** [comment]
A asi by bylo dobré tuto část menu přejmenovat z "Budovy" na  "Stavba na lénech"

**Comment by Tar-Gilkaltar** [comment]
Připomínam tento bod. Je dobre ho udelat jeste pred testovanim!

**Comment by janpadrta** [comment]
done
