### ISSUE TITLE
Chybí malorodní a imperiální syselaad

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#32]
Pokud jsem v malorodě chce to syselaad. Pokud mám hodnost v impériu tak zase Sysel.  Jakou stranou všech ostatních.  Už jsou nachystané myslím jen je spustit

**Comment by Tar-Gilkaltar** [comment]
Imperiální syselaad pro imperátora? Nebude to moc for?

**Comment by Doktoros** [comment]
Imperiální je pro imperátora/regenty, vezíry a dvořany

ta nejvyšší smetánka

**Comment by Tar-Gilkaltar** [comment]
Zda se mi to zbytečné. Přidávané další fóra ale klasicky VIP pro RP chybí

**Comment by Doktoros** [comment]
Nemůžu s tebou souhlasit.  Kazda vrstva potřebuje svoje soukromí. Jsou věci který projednat nemůžeš než mezi těmi kdo jsou zainteresovaní

**Comment by Tar-Gilkaltar** [comment]
OK. Budiž :) Ale uděláš i VIP na RP? :)

**Comment by Tar-Gilkaltar** [comment]
Imperiální je, Malorodní stále není.

**Comment by janpadrta** [comment]
Milane, někde je chyba... při založení MR se musí vytvořit Syselaad a nejspíš i nějakej úvodní topic... při zrušení mr se syselaad musí smazat... taky se při vytvoření musí propojit s malorodem pochopitelně.

Chce to kontrolovat v akci show, jestli je current_user v malorodě, který je přiřazen. Nejspíš to bude chtít rovnou zobrazovat syselaad podle current_user.subhouse... stejně jak se hlídá národní syselaad.

**Comment by minohimself** [comment]
jo ja mr syse nerobil nechal som to na teba preto to asi nepojde :D
