### ISSUE TITLE
Syselaad - Přesměrování ze Syselaadu po založení na správné místo

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#33]
Chybí přesměrování ze Sysla po založení vlákna do jeho náhledu. A při cestě zpět také směřuje jinam. 

Sysel: http://beta.dunaonline.cz/topics/33

Sysel2: http://beta.dunaonline.cz/topics/43

Po založení vlákna v systémovém Syselaadu, je uživatel přesměrovaný na Národní Syselaad.(Zakládám to trochu i pro ověření že je to tak :))
Tak konkrétně je přesměrovaný na /syselaad/13 ??? Což opravdu nevím co to je :D Ale je to špatně. Předpokládám že by měl být přesměrovaný na syselaad je kterém založil vlákno.
To stejný to dělá, když se chci z konkrétního vlákna vrátit na daný syselaad. Klepnu na Systémový (resp. Mezinárodní) syselaad a koukám na přehled vláken národního

**Comment by minohimself** [comment]
hotovo ;) taktiez validacia prazdnych vlakien
