### ISSUE TITLE
IRC - Rozjet IRC

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#42]
Připrav stálé místnosti pro jednotlivé rody, mezinárodní a adminy.

**Comment by simi** [comment]
@Tar-Gilkaltar tak prosím o seznam kanálu i s názvy.

**Comment by Tar-Gilkaltar** [comment]
Atreidove 
Corrino
Ekaz
Harkonnenove
Moritani
Riches
Vernio

Systémové

Mezinárodní

Bude to také chtít nastavit nám adminum operátora na cele IRC.

**Comment by Tar-Gilkaltar** [comment]
Jak s tím bojujes? :)

**Comment by simi** [comment]
![tumblr_mxdd0fbsnh1qdlh1io1_250](https://f.cloud.github.com/assets/193936/1691538/1f9b9850-5e64-11e3-84d3-ca9b7b4a60ca.gif)

**Comment by z0ny** [comment]
tak jsem si u sebe rozjel irc daemona.
pouzil jsem klasicky original ala ircd. Nevim co mas za linux v te virtualce ale ja mam debian, takze klasicky:

```
sudo -i
aptitude install ircd-irc2
```

to nainstaluje irc daemona a hned ho pusti, to my samozrejme nechceme, protoze ho potrebujem nakonfigurovat, takze

```
service ircd-irc2 stop
vim /etc/ircd/ircd.conf
```

nevim co pouzivas za editor... melo by se zobrazit neco jako tohle, popripade tam nejake radky chybi

```
# This is ircd's config-file. Look at
# /usr/share/doc/ircd-irc2/ircd.conf.example.gz and
# and /usr/share/doc/ircd-irc2/INSTALL.* for more detailled information
# and instructions

# M-Line info o serveru
M:server.z0ny.net::Olomouc, CZ:6667:000A

# A-Line administracni info
A:z0ny.net:ircd@z0ny.net:Vitej!::z0nyNet

# Y-Line nastaveni pripojeni
Y:1:90::100:512000:5.5:100.100

# I-Line klientsky nastaveni
I:*:::0:1

# P-Line nastaveni portu
P::::6667:

# C-Line nastaveni linku, je potreba pro services
C:127.0.0.1:<nejaky_heslo>:services.z0ny.net::1
N:127.0.0.1:<nejaky_heslo>:services.z0ny.net::1

# O-Line nastaveni operatoru
O:yaa.z0ny.net:<nejaky_heslo>:z0ny`:0:1
```

pro vysvetleni co jednotlive radky znamenaji je tohle http://www.irc.org/tech_docs/ircnet/INSTALL-4.html, kdyby neco, nemam problem vysvetlit. Jenom dodam heslo tam nepises jako plaintext, ale pouzijes 

```
ircd-mkpasswd
```

zadas heslo a ten text co ti to vrati napises misto nejaky_heslo, to plati i u toho hesla v atheme.conf (viz niz) hesla v C-Line musi souhlasit s tim v atheme.conf

Az se tohle nastavi muze se daemon pustit

```
service ircd-irc2 start
```

Tohle vsak neni vse, ted mas irc server bez niceho, bylo by vhodne tam dat nejaky sluzby co budou drzet prava registrovat uzivatele, atd. atd. 
Me se podarilo rozjet po par problemech atheme, v debian repu je veden jako atheme-services

```
aptitude install atheme-services
```

pri instalaci rve, ze nema zapnute samospusteni, zatim neni potreba resit.
No atheme se sice nainstalovalo, ale neni tam vubec config, relativne dobry navod je zde http://laltromondo.dynalias.net/~iki/informatica/soft/irc_network/ a je tam i odkaz na defaultni config atheme (http://laltromondo.dynalias.net/~iki/informatica/soft/irc_network/atheme.conf.example), config se ulozi do

```
 /etc/atheme/atheme.conf
```

Muj config vypada takto http://server.z0ny.net/atheme.conf 
je tam zakomentovano spousta modulu, ale jinak je to funkcni, jaky modul zapnout/vypnout tj potreba zjistit, samozrejme musel by jsi si prepsat host jmena a heslo

Az tohle bude nastaveno tak zapnes samospusteni ENABLE dat na 1

```
vim /etc/default/atheme-services
```

potom se pripojis na ten irc server a vlezes na tyto kanaly

```
/join &ERRORS
/join &NOTICES
/join &SERVERS
```

a nyni pustis ty sluzby 

```
service atheme-services start
```

pokud mas vse nastaveno dobre tak se ti v &servers zobrazi ze se services pripojili k ircd a v kanale #services se ti pripoji ty sluzby (nicky), pokud je neco spatne tak ti to bude hlasit v &notices a pokud mas vylozene krpal nekde tak v &errors

Dal jsem se tim moc nezabyval, pouze jsem registroval sebe a jeden kanal, neresil jsem prava a tak :)

EDIT: pridadny seznam moznosti pro jednotlivy sluzby http://www.stack.nl/~jilles/irc/atheme-help/

P.S. vypada to slozite a taky to dle me neni uplne jednoduchy, ale to chce cas :D

**Comment by simi** [comment]
Super, tímhle jsem se taky něják prokousal. IRC mi normálně jelo. Horší je to, že netuším jak nastavit ty služby.

**Comment by simi** [comment]
Jinak čas je a klidně hodim přístup na server.

**Comment by Tar-Gilkaltar** [comment]
IRC si hráči udělali "bokem" ale uvnitř hry mu bude lépe :))

**Comment by z0ny** [comment]
No nevedel jsem kam az si dosel, zatim jsem se to dal neresil, zmohla me nemoc tak se me do toho nechtelo :) Jo a tem kecum o tom ze jsem nejlepsi z firmy, bla bla bla bla, atd. to mu neverte, on je hroznej vlezdoprdelka :D Ja pak dam vedet, dle em je lepsi mit irc na serveru, pujde to np propojit primo s webem

**Comment by simi** [comment]
:) Určitě chceme vlastní IRC na vlastním serveru.

**Comment by z0ny** [comment]
muzes me jen rict, co tam mas za distro, irc daemona a sluzby?

**Comment by simi** [comment]
Fedora 13 tuším. ircd a služby atheme. Čili jako ty, až na tu Fedoru.
