### ISSUE TITLE
Trh, zisk z cizího prodeje

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#50]
http://beta.dunaonline.cz/topics/68

těžko říct čím to je. Osobně si myslím že se prodal materiál, kterej jsem jako vicegenerál prodal z malorodu. ale bude to chtít db a trošku pohledat asi...

**Comment by janpadrta** [comment]
tak teď se mi tostalo taky. Pokud prodávám materiál z malorodního a někdo to koupí, tak soláry se připíšou mě místo malorodu. obávám se, že to stejné bude u národa. Ten kdo to z vr/mr poslal, tak to dostane.

**Comment by Doktoros** [comment]
http://beta.dunaonline.cz/topics/65

tady to trošku otestovali.
