### ISSUE TITLE
Pošta - posílání hromadných zpráv

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#51]
Národní pošta musí jít jen národu daného hráče
malorodní jen malorodu
generálům může posílat jen vedení národa (vůdce, mentati) a jde jen generálům daného národa
diplomatickou opět může posílat jen vedení, plus diplomati všem vůdcům, mentatům a diplomatům
_edit Tar_
Landsraadni může posílat jen poslanec všem poslancům
Imperiální poslat celemu imperiu Admin a Imperátor
_/_
tyto zprávy musí být ve výpisu odlišené. nestačí jen filtr.

**Comment by Tar-Gilkaltar** [comment]
Chce to tedy přidat ještě poštu Admina, pro všechny hráče!
