### ISSUE TITLE
správa zařazených zákonů

### ISSUE THREAD

**Issue by janpadrta** [DunaOnline/game#53]
někdo musí mít pravomoc posouvat zákony nahoru a dolů v pořadí a současně vyhazovat nesmyslné. I když to je sporné, možná bych jen dal to posouvání...
smazat zákon z fronty zařazení by mohl jen jeho autor. jakmile se začne projednávat, tak už pochopitelně ne...

**Comment by minohimself** [comment]
A kto ako by mal mat to pravo imp je asi blbost nie ?
