### ISSUE TITLE
Syselaad - VIP Sysel? 

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#68]
Přidat syselaad, který by fungoval jako VIP Land na staré DO.
Hráčům dosti chybí veřejná RP.

Sysel by měl být přístupný pro všechny, ale psát by směli jen členové Landu a možná i diplomaté. 

Jak schvalil dokrot _Lansraadni syselaad v náhledu pro nerenegáty_

**Comment by Doktoros** [comment]
toto je podle mě zbytečné... RP přece může být všude a my bychom to tak měli podporovat a ne jen vyhrazovat speciální forum pro něj...

**Comment by Tar-Gilkaltar** [comment]
Nj ale obyčejní lidé do politiky potom vubec nevidi. A politici se radi ukažou.

**Comment by Doktoros** [comment]
není problém nechat landsraadský syselaad k náhledu pro všechny (nerenegáty), ale rozhodně bych kvůli RP nezakládal nové forum... RP by mělo být všude nejen na jednom fóru...
a politici se můžou předvádět kdekoli...
