### ISSUE TITLE
Volby - General, odchod z malorodu, odchod hráčů z malorodu

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#74]
Clenum malorodu, kteří uz v nem nejsou, zustavaji hlasy. To asi není dobře, ale nevim, co to udela po prepoctu? Zustane dotycny hrac generalem?

http://beta.dunaonline.cz/topics/91

**Comment by minohimself** [comment]
netestoval som to ale dufam to pojde
