### ISSUE TITLE
Syselaad - Řazení, zobrazení nepročteného syseládu

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [DunaOnline/game#75]
Možnost řadit syselaady podle času posledního příspěvku.
Označení nepřečteného syseládu. Ikonka vedle adminské popelnice

**Comment by relmi** [comment]
Kdyz chci zrusit psani prispevku, nejde to pouhym kliknutim na odkaz syselaadu, musim dat tlacitko zpet (2x) a pak to takhle zrusim.
 Neskodilo by tlacitko zrusit psani zpravy a kdyz uz jsme u toho, i tlacitko obnovit v prehledu vlaken jednotlivych syselaadu

**Comment by minohimself** [comment]
takze radenie som spravil, to ze ktore su neprecitane bude zlozitejsie, refresh button ? sak mas F5 keby to moc trebalo viem to spravit

zatvorime to a spravime novy issue na neproctene prispevky na landu oki ?
