### ISSUE TITLE
Cena léna

### ISSUE THREAD

**Issue by Doktoros** [DunaOnline/game#82]
Objevoval jsem léno, na kterém už bylo 7 lén zabráno. Podle všeho mě jeho objevení mělo stát 16.05 mg melanže. Poslal jsem si, abych měl přesně a vyzkoušel, jestli už jste opravili chybu se zaokrouhlováním. Možná se vám teď hnula nějaká desetinná čárka, protože 16.05 jsem měl, 16.05 jsem měl platit a na účtě mi nakonec po objevení zůstalo 0.32 mg :-D

**Comment by relmi** [comment]
doplneni: když chci postavit budovu, na kterou nemám, vyhodí mi chybu, že mi chybí 225,9999999999999997 solárů.
