### ISSUE TITLE
Chyba: rozdelovani slov v prispevku

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#89]
slovo v prispevku ve vlaknu je na konci useknuto a pokracuje na novem radku, namisto hozeni celeho slova na novy radek.

**Comment by relmi** [comment]
minohimself 
14.10.2013 11:05
break-word, miesto break-all

**Comment by relmi** [comment]
http://beta.dunaonline.cz/topics/170

**Comment by Tar-Gilkaltar** [comment]
ou pardon to je moje blbost :)
