### ISSUE TITLE
Bug: Presun materialu mezi leny

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#93]
Na DP mam 7 materialu, na druhem lenu 1100 materialu. At se snazim posilat material (1 kus) z kterehokoliv lena na to druhe, tak koncim hlaskou "Nedostatek surovin na odchozím léně"

**Comment by relmi** [comment]
http://beta.dunaonline.cz/topics/186

**Comment by minohimself** [comment]
to uz hadam ide
