### ISSUE TITLE
Navrh: poznamka u vypisu

### ISSUE THREAD

**Issue by relmi** [DunaOnline/game#99]
při posílání surovin bych uvítal možnost připsat "poznámku", která se uloží do logu ... hráč tak může připsat, z jakých důvodů si danou surovinu vybral ... zlepšuje to "vedení národního účetnictví"

**Comment by janpadrta** [comment]
Přidat jen text_field při posílání surovin a ten zapsat do poznámky. jinam se to ukládat nemusí.
